# Enable all rules that are disabled by default, other than `Style/GuardClause`

Lint/ComparisonToBoolean:
  Enabled: true

Layout/LineLength:
  Enabled: true
  MaxLength: 80

Style/LargeNumbers:
  Enabled: true

Style/PredicateName:
  Enabled: true

# Disable warnings about `.not_nil!` as we have some legitimate uses for it

Lint/NotNil:
  Enabled: false
