app = "t-cal"

[env]
  HOST = "0.0.0.0"
  PORT = "8080"
  ORIGIN = "https://tcal.digitalcora.net"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 2
    timeout = "2s"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
