app = "t-cal"
primary_region = "ewr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  HOST = "0.0.0.0"
  ORIGIN = "https://tcal.digitalcora.net"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/_health"
    protocol = "http"
